Update UG
AY2021S2-CS2103T-W14-1/tp pull request #237
Opened 2021-04-09 09:06 UTC by Assyarul

Add Friends Section to explain each field for Person.

Fixes #153, #172, #185, #195

2021-04-09 14:23 UTC, ivantjh requested changes

2021-04-09 14:23 UTC, ivantjh commented on docs/UserGuide.md
> +This field is what uniquely identifies each friend in FriendDex.
Can add in "Names are case-insensitive in FriendDex. This means that FriendDex interprets "John Doe" and "JoHn DoE" as the same name."

2021-04-09 14:23 UTC, ivantjh commented on docs/UserGuide.md
> +This field can take any values, but it should not be blank.
Can add in "It is okay for two friends to share the same address. They could be siblings stored in FriendDex."

2021-04-09 14:23 UTC, ivantjh commented on docs/UserGuide.md
> +A positive amount of debt would mean that you owe your friend the specified amount.
Can we switch the definition for positive and negative debt. I feel it is more intuitive this way but let me know if you think otherwise.

2021-04-10 13:53 UTC, chesterhow approved these changes
LGTM

2021-04-10 13:53 UTC, chesterhow commented on docs/UserGuide.md
> +This field should follow the following date format: `dd-MM-yyyy` e.g `01-01-2020`
Should we document that the birthday should not be a date in the future?

2021-04-10 15:27 UTC, ivantjh approved these changes
lgtm!

2021-04-10 15:52 UTC, merged