Add autocomplete for commands
AY2021S2-CS2103T-W14-1/tp pull request #72
Opened 2021-03-24 02:43 UTC by ivantjh

- Need to maintain another list of strings used for autocompletion. They are in `Commands` for now.

2021-03-24 10:57 UTC, chesterhow approved these changes

2021-03-24 10:57 UTC, chesterhow commented on src/main/resources/view/Template.css
> +    -fx-background-color: #ffffff;
Would be better if we used the theme's colours here

2021-03-24 10:59 UTC, lue97 requested changes
Use $c0 to $cf for styling

2021-03-25 17:16 UTC, lue97 approved these changes
lgtm

2021-03-26 01:05 UTC, merged